apiVersion: v1
kind: Secret
metadata:
    namespace: todo
    name: pg-apkey
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:fmkC4Sh0E+LuuYFcDHR/da56vxljyOJaXK4e0U0R8zSYrkLO,iv:i87jTsJDhw6V+LenpHIpEf31pn25PQCbUcP0+Y2tqGs=,tag:/wDlFaK9tBrIqYY9Ylkopg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rpfml8gcj6gxku706nf76u0wp7eusrh80wdjqrkfvqcpnpa8pprqgce3a5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SjdJMnFoY0dQR3VRTlFI
            K2ZPQkQ1UW43U2gvdSsrUkhrRm9uREZQQ1ZrCjRUaCtLUUphc05iN2hIZFhiVDY2
            QWhWRkIzemZSVnJ3T3YrVUlWLzdIOFUKLS0tIGxDU2JmOFYxT0hWT2pkSEp4ZXRa
            SS8rNzRmaEdQZkJRSHhhL0hhT2VMaDAK1SORw6x1mu3g57M7YRxTqXWzIYx3kP7I
            wFTsYaU08HaR+pCM84385PIZKYhaGZPIAZO4Pt7ZYvX4ujujXty/Yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-28T12:59:25Z"
    mac: ENC[AES256_GCM,data:47l/hKE0GedLj2ZIxf2VTkPjv5xb73O97bpezECUBbbhZ64Sn6iI7cUAB5l/Z8vA07KwbgZQGfx9mwrewXVtcU34AzW+fKHeFB2rgSE6bpnptHbbHEEemYLKFFEEocA0AmsKUjBFoPYTrrVWKxF0oDjrytI3i4qGIriPzhkozhQ=,iv:Z3l1UVg1NpyOY9QIUnz4C3QiI6UHWXjuitoHFxdEMsM=,tag:h4MRdtJMIfffRAIWXGKp1w==,type:str]
    pgp: []
    encrypted_regex: ^(stringData)$
    version: 3.7.3
