apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-todo-cronjob
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kube-todo-cronjob
            image: nettivastaava/kube-todo-cronjob:8
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure