apiVersion: v1
kind: Service
metadata:
  name: todo-project-front-dep-svc
spec:
  type: ClusterIP
  selector:
    app: todo-project-front-dep
  ports:
    - port: 2346
      protocol: TCP
      targetPort: 3000