name: Release application

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: todo-cluster
  GKE_ZONE: europe-north1-b
  FRONT_IMAGE: nettivastaava/kube-todo-front
  BACK_IMAGE: nettivastaava/kube-todo-project

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          export_default_credentials: true

      - run: gcloud --quiet auth configure-docker

      - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Build front end
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$FRONT_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" \
            ./todo-project/todo-front

      - name: Build back end
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$BACK_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" \
            ./todo-project/todo-app

      - name: Publish front end
        run: |-
          docker push "gcr.io/$PROJECT_ID/$FRONT_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"

      - name: Publish back end
        run: |-
          docker push "gcr.io/$PROJECT_ID/$BACK_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Deploy back end
        run: |-
          kubectl create namespace todo
          kustomize edit set image gcr.io/PROJECT_ID/BACK_IMAGE=gcr.io/$PROJECT_ID/$BACK_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
          kustomize build . | kubectl apply -f - --validate=false 
          kubectl rollout status deployment $BACK_IMAGE
          kubectl get services -o wide

      - name: Deploy front end
        run: |-
          kustomize edit set image gcr.io/PROJECT_ID/FRONT_IMAGE=gcr.io/$PROJECT_ID/$FRONT_IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment $FRONT_IMAGE
          kubectl get services -o wide


